version: "3"

volumes:
  postgres_data: { }

services:
  api:
    container_name: "presenze-api"
    build: .
    ports:
      - "4040:4040"
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    restart: always

  db:
    container_name: "presenze-postgres"
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_presenze