export const errCodes = {
    ERR_CLASS_HAS_STUDENTS: "ERR_CLASS_HAS_STUDENTS",
    ERR_CLASS_NOT_FOUND: "ERR_CLASS_NOT_FOUND",
    ERR_COURSE_HAS_STUDENTS: "ERR_COURSE_HAS_STUDENTS",
    ERR_COURSE_NOT_FOUND: "ERR_COURSE_NOT_FOUND",
    ERR_STUDENTS_NOT_IN_SAME_SCHOOL_YEAR: "ERR_STUDENTS_NOT_IN_SAME_SCHOOL_YEAR",
    ERR_STUDENTS_NOT_SPECIFIED: "ERR_STUDENTS_NOT_SPECIFIED",
    ERR_STUDENT_HAS_COURSES: "ERR_STUDENT_HAS_COURSES",
    ERR_STUDENT_NOT_FOUND: "ERR_STUDENT_NOT_FOUND",
    ERR_YEAR_NOT_FOUND: "ERR_YEAR_NOT_FOUND",
    ERR_UNKNOWN: "ERR_UNKNOWN"
}

